module.exports = {
  extends: ['influencer/react-app'],
  rules: {
    // conflicts
    'import/no-extraneous-dependencies': 'off',
    '@typescript-eslint/no-unsafe-assignment': 'off',
    '@typescript-eslint/no-unsafe-call': 'off',
    '@typescript-eslint/no-unsafe-member-access': 'off',
    '@typescript-eslint/no-unsafe-argument': 'off',
    'react/react-in-jsx-scope': 'off',
    'testing-library/prefer-screen-queries': 'warn',
    'testing-library/prefer-presence-queries': 'warn',
    'testing-library/no-node-access': 'warn',
    '@typescript-eslint/no-shadow': 'off',
    'react/jsx-props-no-spreading': 'warn', // discuss with the team
    '@typescript-eslint/no-unsafe-return': 'off',
    '@typescript-eslint/naming-convention': 'off',
    'react-hooks/exhaustive-deps': 'off',
    '@typescript-eslint/ban-types': 'off',
    'react/button-has-type': 'off',
    'react/no-array-index-key': 'warn',
    'no-plusplus': 'warn', // discuss with the team
    '@typescript-eslint/no-misused-promises': 'off',
    'no-unsafe-optional-chaining': 'off',
    '@typescript-eslint/no-unused-vars': 'warn',
    'no-restricted-syntax': 'off',
    'promise/catch-or-return': 'off',
    'promise/always-return': 'off',
    'react/no-unescaped-entities': 'off',
    'react/no-unused-prop-types': 'off',
    '@typescript-eslint/no-use-before-define': 'off',
    'react/no-unstable-nested-components': 'off',
    'no-param-reassign': 'off',
    radix: 'off',
    '@typescript-eslint/no-unused-expressions': 'off',
    'import/no-cycle': 'off',
    'react/destructuring-assignment': 'off',
    'guard-for-in': 'off',
    'no-prototype-builtins': 'off',
    'no-restricted-globals': 'off',
    'consistent-return': 'off',
  },
};
